Responsive design
js-tasks-ru/htmlcss-20220519_night-raven pull request #17
Opened 2022-06-06 11:31 UTC by brinevdev

2022-06-06 11:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-06 14:34 UTC, GSemikozov requested changes

2022-06-06 15:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-06 15:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 18:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 18:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 18:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 18:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 19:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 19:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-08 19:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-13 12:37 UTC, brinevdev commented on pages/template/tepmlate.css
> +@import url(../../assets/css/main.css);
да, поменял

2022-06-13 14:58 UTC, GSemikozov approved these changes

2022-06-13 14:58 UTC, merged