Toggler
js-tasks-ru/htmlcss-20220519_night-raven pull request #20
Opened 2022-06-09 14:25 UTC by brinevdev

2022-06-09 15:50 UTC, GSemikozov requested changes

2022-06-09 15:50 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +form {
см коммент в ПР по чекбосу.

2022-06-09 15:50 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    opacity: 0;
при таком варианте элемент будет по-прежнему занимать место и быть доступным, перекрывая собой другие элементы

2022-06-13 11:52 UTC, brinevdev commented on 07-lection5/03-toggler/toggler.css
> +form {
поменял

2022-06-13 11:52 UTC, brinevdev commented on 07-lection5/03-toggler/toggler.css
> +    opacity: 0;
поменял

2022-06-13 14:59 UTC, GSemikozov approved these changes

2022-06-13 14:59 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-06-13 15:00 UTC, GSemikozov approved these changes

2022-06-13 15:00 UTC, merged